### ISSUE TITLE
vqt_name incorrectly indexes the fonts

### ISSUE THREAD

**Issue by tevorbl** [emutos/emutos#32] opened 2021-10-15 14:50 UTC
attached is a gdos test program and a simple assign.sys,
correct output with TOS2.06 is:
```

3 screen fonts loaded
font 1, 6x6 system font, id = 1
font 2, Swiss, id = 2
font 3, Dutch, id = 14
font 4, Typewriter, id = 15

```

and with emutos, the corersponding output is:
```
3 screen fonts loaded
font 1, 6x6 system font, id = 1
font 2, 8x8 system font, id = 1
font 3, 8x16 system font, id = 1
font 4, Swiss, id = 2

```
[testgdos.c.txt](https://github.com/emutos/emutos/files/7354078/testgdos.c.txt)

[assign.sys.txt](https://github.com/emutos/emutos/files/7354086/assign.sys.txt)

Looking in the file **vdi_text.c**, in function **vdi_vqt_name()**, the loop is counting individual fonts. It should be counting only font families, ie fonts with distinctive font ids, as is done in vdi_vst_load_fonts().

Also, comparing these 2 functions, I would expect vdi_vqt_name() to depend on the workstation, using   **vwk->loaded_fonts** as a base for the fontchain, and then not needing a double loop.   OTOH, I don't know this code, so perhaps I am missing something.

**Comment by mfro0** [comment] 2021-10-16 09:08
Checked with fVDI and TOS output is the exact same than EmuTOS output for me (checked in Hatari with Falcon emulation, but I would assume that shouldn't make a difference).

TOS output:
```
30 new screen fonts loaded
font 0, 6x6 system font, id = 1
font 1, 6x6 system font, id = 1
font 2, Comic Sans MS Regular, id = 7059
font 3, Courier New Bold, id = 7203
font 4, Trebuchet MS Bold, id = 7612

```
EmuTOS output:

```
30 new screen fonts loaded
font 0, 6x6 system font, id = 1
font 1, 6x6 system font, id = 1
font 2, Comic Sans MS Regular, id = 7059
font 3, Courier New Bold, id = 7203
font 4, Trebuchet MS Bold, id = 7612
```
...

I admit that I fixed your code first as there were small imperfections (probably not the cause of the differences you are experiencing, but anyway):

- `vqt_fontinfo()` array indexing is zero-based
- fonts loaded with `vst_load_fonts()` are appended to the font list. The number of fonts already present before `vst_load_fonts()` is available from `work_out[10]` after opening the virtual workstation.

To create a list of all available fonts, your loop should look like this, then:
     `for( font_idx=0; font_idx<new_fonts+work_out[10]; font_idx++ ) {`

To further track down the differences you are observing, your GDOS setup and fonts are most likely required. Would you be able to make them available somehow?

**Comment by tevorbl** [comment] 2021-10-16 09:50
Hi,
Thanks for the response.

My GDOS setup is the standard GDOS 1.1, fonts are standard atari fonts distributed with GDOS. 
Here's a link -> http://www.atarimania.com/utility-atari-st-gdos-distribution-disk_25889.html
My assign.sys file is already posted above.

The test should be repeatable with any GDOS and any gem fonts.

**Closed as completed** 2021-10-18 22:58 UTC

**Comment by tevorbl** [comment] 2021-10-19 10:41
Many thanks for the quick fix.
I'll start using this right away.
